## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Windsoredge Research"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Market Research Consultancy"
  logo = "images/logo-small.png"
  favicon = true
  fontFamily = "Open Sans, sans-serif"
  hugo_css_minify = false
  postcss = false


[Params.social]
  email = "info@windsoredge-research.com"
  telephone = "+44 (0)7768 998491"
  linkedin = "https://linkedin.com"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]
  sass = ["sass/main.scss", "sass/no-script.scss"]
  sass_output = "css"